-- Création des tables
CREATE TABLE Filiere (
    id_fil NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_fil VARCHAR2(50) NOT NULL,
    nbr_etudiants INT NOT NULL
);

CREATE TABLE Professeur (
    id_prof NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(50) NOT NULL,
    prenom VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL
);

CREATE TABLE Etudiant (
    cne VARCHAR2(10) PRIMARY KEY,
    Nom VARCHAR2(40) NOT NULL,
    Prenom VARCHAR2(40) NOT NULL,
    Email VARCHAR2(50) NOT NULL,
    id_fil NUMBER,
    FOREIGN KEY (id_fil) REFERENCES Filiere(id_fil)
);

CREATE TABLE Module (
    id_mod NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom_mod VARCHAR2(50) NOT NULL,
    id_fil NUMBER,
    id_prof NUMBER,
    FOREIGN KEY (id_fil) REFERENCES Filiere(id_fil),
    FOREIGN KEY (id_prof) REFERENCES Professeur(id_prof)
);

CREATE TABLE Absence (
    cne VARCHAR2(10),
    id_mod NUMBER,
    date_abs DATE NOT NULL,
    PRIMARY KEY (cne, id_mod, date_abs),
    FOREIGN KEY (cne) REFERENCES Etudiant(cne),
    FOREIGN KEY (id_mod) REFERENCES Module(id_mod)
);
